const STORAGE_KEY='bizops_state_v1';
const initialState={customers:[{name:'サンプル顧客 A',plan:'Pro',monthly:120000,status:'継続中',owner:'田中',nextAction:'月次レビュー'},{name:'サンプル顧客 B',plan:'Standard',monthly:48000,status:'確認中',owner:'佐藤',nextAction:'請求先確認'},{name:'サンプル顧客 C',plan:'Enterprise',monthly:260000,status:'継続中',owner:'鈴木',nextAction:'追加ID提案'},{name:'サンプル顧客 D',plan:'Starter',monthly:18000,status:'要対応',owner:'山本',nextAction:'利用状況確認'}],reservations:[{id:'BKG-101',time:'10:30',title:'オンライン商談',type:'新規相談',owner:'田中',status:'未確認'},{id:'BKG-102',time:'14:00',title:'導入サポート',type:'既存顧客',owner:'佐藤',status:'確認済み'}],monthly:[42,54,50,62,78,88]};
const $=selector=>document.querySelector(selector);
function loadState(){return JSON.parse(localStorage.getItem(STORAGE_KEY)||JSON.stringify(initialState))}
function saveState(state){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
let state=loadState();
const money=value=>`¥${Number(value).toLocaleString('ja-JP')}`;
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function filteredCustomers(){const term=$('#search').value.trim().toLowerCase();const status=$('#statusFilter').value;return state.customers.filter(c=>{const hay=`${c.name} ${c.plan} ${c.status} ${c.owner} ${c.nextAction}`.toLowerCase();return (!term||hay.includes(term))&&(status==='all'||c.status===status)})}
function renderMetrics(){const revenue=state.customers.filter(c=>c.status==='継続中').reduce((sum,c)=>sum+Number(c.monthly||0),0);$('#revenue').textContent=money(revenue);$('#customersMetric').textContent=state.customers.filter(c=>c.status==='継続中').length;$('#bookingsMetric').textContent=state.reservations.length;$('#riskMetric').textContent=state.customers.filter(c=>c.status==='要対応').length}
function renderChart(){const labels=['1月','2月','3月','4月','5月','6月'];$('#chart').innerHTML=state.monthly.map((height,index)=>`<div class="bar" style="height:${height}%" data-label="${labels[index]}"></div>`).join('')}
function renderCustomers(){const rows=filteredCustomers();$('#customerRows').innerHTML=rows.length?rows.map((c,index)=>`<tr><td>${escapeHtml(c.name)}</td><td>${escapeHtml(c.plan)}</td><td>${money(c.monthly)}</td><td><select data-customer-status="${index}"><option ${c.status==='継続中'?'selected':''}>継続中</option><option ${c.status==='確認中'?'selected':''}>確認中</option><option ${c.status==='要対応'?'selected':''}>要対応</option></select></td><td>${escapeHtml(c.owner)}</td><td>${escapeHtml(c.nextAction)}</td></tr>`).join(''):'<tr><td class="empty" colspan="6">条件に合う顧客がありません。</td></tr>';document.querySelectorAll('[data-customer-status]').forEach(select=>{select.addEventListener('change',event=>{const visible=filteredCustomers();const item=visible[Number(event.target.dataset.customerStatus)];const target=state.customers.find(c=>c.name===item.name&&c.owner===item.owner);target.status=event.target.value;saveState(state);renderAll()})})}
function renderReservations(){const term=$('#search').value.trim().toLowerCase();const rows=state.reservations.filter(r=>!term||`${r.title} ${r.type} ${r.owner} ${r.status}`.toLowerCase().includes(term));$('#reservationList').innerHTML=rows.length?rows.map(r=>`<article class="reservation-card ${r.status==='確認済み'?'done':''}"><strong>${escapeHtml(r.time)} ${escapeHtml(r.title)}</strong><span>担当: ${escapeHtml(r.owner)} / 種別: ${escapeHtml(r.type)} / 状態: ${escapeHtml(r.status)}</span><button class="btn ${r.status==='確認済み'?'':'primary'}" data-booking="${r.id}">${r.status==='確認済み'?'未確認に戻す':'確認済みにする'}</button></article>`).join(''):'<p class="empty">予約はありません。</p>';document.querySelectorAll('[data-booking]').forEach(button=>button.addEventListener('click',()=>{const item=state.reservations.find(r=>r.id===button.dataset.booking);item.status=item.status==='確認済み'?'未確認':'確認済み';saveState(state);renderAll()}))}
function renderAll(){renderMetrics();renderChart();renderCustomers();renderReservations()}
function exportCsv(){const headers=['name','plan','monthly','status','owner','nextAction'];const rows=state.customers.map(c=>headers.map(key=>`"${String(c[key]??'').replaceAll('"','""')}"`).join(','));const blob=new Blob([[headers.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='customers.csv';a.click();URL.revokeObjectURL(url)}
document.addEventListener('DOMContentLoaded',()=>{renderAll();document.querySelectorAll('.side-nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.side-nav button').forEach(item=>item.setAttribute('aria-selected','false'));button.setAttribute('aria-selected','true');$('#pageTitle').textContent=button.textContent}));$('#search').addEventListener('input',renderAll);$('#statusFilter').addEventListener('change',renderAll);$('#customerForm').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));state.customers.unshift({...data,monthly:Number(data.monthly)});saveState(state);event.currentTarget.reset();renderAll()});$('#bookingForm').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));state.reservations.unshift({id:`BKG-${Date.now().toString().slice(-5)}`,...data,status:'未確認'});saveState(state);event.currentTarget.reset();renderAll()});$('#toggleChart').addEventListener('click',()=>{state.monthly=state.monthly.map(value=>Math.max(35,Math.min(95,value+Math.round((Math.random()*18)-6))));saveState(state);renderAll()});$('#refreshBtn').addEventListener('click',renderAll);$('#exportCsv').addEventListener('click',exportCsv);$('#resetDemo').addEventListener('click',()=>{if(confirm('デモデータを初期状態に戻しますか？')){state=structuredClone(initialState);saveState(state);renderAll()}})});
